import { useEffect,useMemo,useState } from "react";
import { BookOpen,Boxes,ChevronRight,LayoutDashboard,LogOut,Menu,PenLine,Plus,Search,Trash2,Users,X } from "lucide-react";
import { api } from "./api.js";

const blankTerm={category_id:"",group_id:"",name_zh:"",name_en:"",description:"",visual_type:"generic",status:"published",sort_order:0};
const blankCategory={slug:"",label:"",title:"",sort_order:0,is_visible:true};
const blankGroup={category_id:"",name:"",sort_order:0};

function Login({onLogin}){
  const [form,setForm]=useState({username:"admin",password:""}),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const submit=async event=>{event.preventDefault();setBusy(true);setError("");try{const data=await api("/api/admin/login",{method:"POST",body:JSON.stringify(form)});onLogin(data.user)}catch(e){setError(e.message)}finally{setBusy(false)}};
  return <div className="admin-login"><form onSubmit={submit}><a href="/" className="admin-login-brand"><img src="/assets/ai-builder-team-logo.svg" alt=""/><span>AI Builder Team 管理端</span></a><h1>登录管理后台</h1><p>管理分类、分组、术语内容与发布状态。</p><label>用户名<input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} autoComplete="username"/></label><label>密码<input type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} autoComplete="current-password" autoFocus/></label>{error&&<div className="form-error">{error}</div>}<button className="primary-button" disabled={busy}>{busy?"正在登录…":"登录"}</button><a href="/" className="back-link">返回公开站点</a></form></div>
}

function Modal({title,onClose,children}){return <div className="admin-modal-backdrop"><div className="admin-modal"><header><h2>{title}</h2><button onClick={onClose} aria-label="关闭"><X size={20}/></button></header>{children}</div></div>}

export function AdminApp(){
  const [user,setUser]=useState(null),[checking,setChecking]=useState(true),[view,setView]=useState("dashboard"),[dashboard,setDashboard]=useState(null),[categories,setCategories]=useState([]),[groups,setGroups]=useState([]),[terms,setTerms]=useState([]),[query,setQuery]=useState(""),[filterCategory,setFilterCategory]=useState(""),[modal,setModal]=useState(null),[notice,setNotice]=useState(""),[menu,setMenu]=useState(false);
  useEffect(()=>{api("/api/admin/me").then(data=>setUser(data.user)).catch(()=>{}).finally(()=>setChecking(false))},[]);
  const loadCategories=async()=>{const data=await api("/api/admin/categories");setCategories(data.categories)};
  const loadGroups=async categoryId=>{const data=await api(`/api/admin/groups${categoryId?`?category_id=${categoryId}`:""}`);setGroups(data.groups)};
  const loadTerms=async()=>{const params=new URLSearchParams();if(query)params.set("q",query);if(filterCategory)params.set("category_id",filterCategory);const data=await api(`/api/admin/terms?${params}`);setTerms(data.terms)};
  const refresh=async()=>{if(view==="dashboard")setDashboard(await api("/api/admin/dashboard"));if(view==="categories")await loadCategories();if(view==="groups")await Promise.all([loadCategories(),loadGroups()]);if(view==="terms"){await Promise.all([loadCategories(),loadGroups(),loadTerms()])}};
  useEffect(()=>{if(user)refresh().catch(e=>setNotice(e.message))},[user,view]);
  useEffect(()=>{if(user&&view==="terms"){const timer=setTimeout(()=>loadTerms().catch(e=>setNotice(e.message)),200);return()=>clearTimeout(timer)}},[query,filterCategory]);
  const flash=message=>{setNotice(message);setTimeout(()=>setNotice(""),2200)};
  const logout=async()=>{await api("/api/admin/logout",{method:"POST"});setUser(null)};
  const saveTerm=async(form)=>{const editing=Boolean(form.id);await api(`/api/admin/terms${editing?`/${form.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(form)});setModal(null);await loadTerms();flash(editing?"术语已更新":"术语已创建")};
  const saveCategory=async(form)=>{const editing=Boolean(form.id);await api(`/api/admin/categories${editing?`/${form.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(form)});setModal(null);await loadCategories();flash(editing?"分类已更新":"分类已创建")};
  const saveGroup=async(form)=>{const editing=Boolean(form.id);await api(`/api/admin/groups${editing?`/${form.id}`:""}`,{method:editing?"PUT":"POST",body:JSON.stringify(form)});setModal(null);await loadGroups();flash(editing?"分组已更新":"分组已创建")};
  const remove=async(type,id)=>{if(!confirm(type==="terms"?"确定删除这个术语？":"删除分类会同时删除其分组和术语，确定继续？"))return;await api(`/api/admin/${type}/${id}`,{method:"DELETE"});await refresh();flash("已删除")};
  const nav=[{id:"dashboard",label:"概览",icon:LayoutDashboard},{id:"terms",label:"术语管理",icon:BookOpen},{id:"groups",label:"分组管理",icon:Menu},{id:"categories",label:"分类管理",icon:Boxes}];
  if(checking)return <div className="page-state"><div className="spinner"/></div>;
  if(!user)return <Login onLogin={setUser}/>;
  return <div className="admin-shell">
    <aside className={menu?"admin-sidebar open":"admin-sidebar"}><a className="admin-brand" href="/"><img src="/assets/ai-builder-team-logo.svg" alt=""/><b>AI Builder</b><span>TEAM 管理端</span></a><nav>{nav.map(item=>{const Icon=item.icon;return <button key={item.id} className={view===item.id?"active":""} onClick={()=>{setView(item.id);setMenu(false)}}><Icon size={18}/>{item.label}<ChevronRight size={15}/></button>})}</nav><div className="admin-user"><div><b>{user.username}</b><span>超级管理员</span></div><button onClick={logout} title="退出登录"><LogOut size={18}/></button></div></aside>
    <main className="admin-main"><header className="admin-top"><button className="admin-menu" onClick={()=>setMenu(!menu)}><Menu size={20}/></button><div><h1>{nav.find(item=>item.id===view)?.label}</h1><p>{view==="dashboard"?"掌握内容规模与运营数据":view==="terms"?"编辑术语内容和发布状态":view==="groups"?"管理分类下的内容分组":"组织公开站点的一级分类"}</p></div><a href="/" target="_blank">查看公开站点</a></header>
      {view==="dashboard"&&<Dashboard data={dashboard}/>} {view==="terms"&&<TermsView terms={terms} categories={categories} groups={groups} query={query} setQuery={setQuery} filterCategory={filterCategory} setFilterCategory={setFilterCategory} onAdd={()=>setModal({type:"term",data:{...blankTerm,category_id:categories[0]?.id||""}})} onEdit={term=>setModal({type:"term",data:term})} onDelete={id=>remove("terms",id)}/>} {view==="groups"&&<GroupsView groups={groups} categories={categories} onAdd={()=>setModal({type:"group",data:{...blankGroup,category_id:categories[0]?.id||""}})} onEdit={data=>setModal({type:"group",data})} onDelete={id=>remove("groups",id)}/>} {view==="categories"&&<CategoriesView categories={categories} onAdd={()=>setModal({type:"category",data:blankCategory})} onEdit={data=>setModal({type:"category",data})} onDelete={id=>remove("categories",id)}/>}
    </main>
    {notice&&<div className="admin-toast">{notice}</div>}
    {modal?.type==="term"&&<Modal title={modal.data.id?"编辑术语":"新增术语"} onClose={()=>setModal(null)}><TermForm initial={modal.data} categories={categories} allGroups={groups} onLoadGroups={loadGroups} onSave={saveTerm} onCancel={()=>setModal(null)}/></Modal>}
    {modal?.type==="group"&&<Modal title={modal.data.id?"编辑分组":"新增分组"} onClose={()=>setModal(null)}><GroupForm initial={modal.data} categories={categories} onSave={saveGroup}/></Modal>}
    {modal?.type==="category"&&<Modal title={modal.data.id?"编辑分类":"新增分类"} onClose={()=>setModal(null)}><CategoryForm initial={modal.data} onSave={saveCategory}/></Modal>}
  </div>
}

function Dashboard({data}){if(!data)return <div className="admin-loading">正在汇总数据…</div>;const cards=[{label:"术语总数",value:data.stats.terms,icon:BookOpen},{label:"分类数量",value:data.stats.categories,icon:Boxes},{label:"草稿",value:data.stats.drafts,icon:PenLine},{label:"问卷反馈",value:data.stats.surveyResponses,icon:Users}];return <div className="admin-dashboard"><section className="stat-grid">{cards.map(item=>{const Icon=item.icon;return <article key={item.label}><div><span>{item.label}</span><strong>{item.value}</strong></div><Icon size={21}/></article>})}</section><section className="admin-panels"><div><header><h2>最近更新</h2><span>最近 8 条</span></header><div className="recent-list">{data.recent.map(term=><div key={term.id}><span className="term-avatar">{term.name_zh.slice(0,1)}</span><div><b>{term.name_zh}</b><span>{term.category} · {term.updated_at}</span></div><em className={term.status}>{term.status==="published"?"已发布":"草稿"}</em></div>)}</div></div><div><header><h2>获客渠道</h2><span>问卷统计</span></header><div className="source-list">{data.sources.length?data.sources.map(source=><div key={source.source}><span>{source.source}</span><b>{source.count}</b></div>):<p>暂无问卷数据</p>}</div></div></section></div>}

function TermsView({terms,categories,query,setQuery,filterCategory,setFilterCategory,onAdd,onEdit,onDelete}){return <section className="admin-section"><div className="table-toolbar"><label><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="搜索中文、英文或描述"/></label><select value={filterCategory} onChange={e=>setFilterCategory(e.target.value)}><option value="">全部分类</option>{categories.map(category=><option value={category.id} key={category.id}>{category.label}</option>)}</select><button className="primary-button" onClick={onAdd}><Plus size={17}/>新增术语</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>术语</th><th>分类 / 分组</th><th>状态</th><th>更新时间</th><th></th></tr></thead><tbody>{terms.map(term=><tr key={term.id}><td><b>{term.name_zh}</b><span>{term.name_en||"-"}</span></td><td>{term.category}<span>{term.group_name}</span></td><td><em className={term.status}>{term.status==="published"?"已发布":"草稿"}</em></td><td>{term.updated_at}</td><td><button onClick={()=>onEdit(term)} title="编辑"><PenLine size={16}/></button><button onClick={()=>onDelete(term.id)} title="删除"><Trash2 size={16}/></button></td></tr>)}</tbody></table>{!terms.length&&<div className="table-empty">没有符合条件的术语</div>}</div></section>}

function CategoriesView({categories,onAdd,onEdit,onDelete}){return <section className="admin-section"><div className="section-actions"><div><h2>一级分类</h2><p>控制公开站点顶部类别与展示顺序。</p></div><button className="primary-button" onClick={onAdd}><Plus size={17}/>新增分类</button></div><div className="category-admin-grid">{categories.map(category=><article key={category.id}><span className="category-order">{String(category.sort_order+1).padStart(2,"0")}</span><div><h3>{category.label}</h3><p>{category.title}</p><small>{category.slug} · {category.term_count} 个术语</small></div><em className={category.is_visible?"published":"draft"}>{category.is_visible?"显示中":"已隐藏"}</em><div><button onClick={()=>onEdit(category)}><PenLine size={16}/></button><button onClick={()=>onDelete(category.id)}><Trash2 size={16}/></button></div></article>)}</div></section>}

function GroupsView({groups,categories,onAdd,onEdit,onDelete}){const label=id=>categories.find(c=>String(c.id)===String(id))?.label||"-";return <section className="admin-section"><div className="section-actions"><div><h2>内容分组</h2><p>分组决定公开目录侧栏和卡片区块。</p></div><button className="primary-button" onClick={onAdd}><Plus size={17}/>新增分组</button></div><div className="category-admin-grid">{groups.map(group=><article key={group.id}><span className="category-order">{String(group.sort_order+1).padStart(2,"0")}</span><div><h3>{group.name}</h3><p>所属分类：{label(group.category_id)}</p><small>分组 ID {group.id}</small></div><div><button onClick={()=>onEdit(group)} title="编辑"><PenLine size={16}/></button><button onClick={()=>onDelete(group.id)} title="删除"><Trash2 size={16}/></button></div></article>)}</div></section>}

function TermForm({initial,categories,allGroups,onLoadGroups,onSave,onCancel}){const [form,setForm]=useState(initial),[groups,setGroups]=useState(allGroups.filter(group=>String(group.category_id)===String(initial.category_id))),[error,setError]=useState("");useEffect(()=>{onLoadGroups(form.category_id).then(()=>{})},[]);const categoryChanged=async value=>{const data=await api(`/api/admin/groups?category_id=${value}`);setGroups(data.groups);setForm({...form,category_id:value,group_id:data.groups[0]?.id||""})};const submit=async e=>{e.preventDefault();setError("");try{await onSave(form)}catch(err){setError(err.message)}};return <form className="admin-form" onSubmit={submit}><div className="form-row"><label>所属分类<select value={form.category_id} onChange={e=>categoryChanged(e.target.value)} required><option value="">请选择</option>{categories.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label>所属分组<select value={form.group_id} onChange={e=>setForm({...form,group_id:e.target.value})} required><option value="">请选择</option>{groups.map(g=><option value={g.id} key={g.id}>{g.name}</option>)}</select></label></div><div className="form-row"><label>中文名称<input value={form.name_zh} onChange={e=>setForm({...form,name_zh:e.target.value})} required/></label><label>英文名称<input value={form.name_en} onChange={e=>setForm({...form,name_en:e.target.value})}/></label></div><label>大白话描述<textarea rows="4" value={form.description} onChange={e=>setForm({...form,description:e.target.value})} required/></label><div className="form-row"><label>卡片演示<select value={form.visual_type} onChange={e=>setForm({...form,visual_type:e.target.value})}>{["generic","browser","component","state","markdown","html","table","chart","flow"].map(v=><option key={v}>{v}</option>)}</select></label><label>发布状态<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="published">已发布</option><option value="draft">草稿</option></select></label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><button type="button" onClick={onCancel}>取消</button><button className="primary-button">保存术语</button></div></form>}

function GroupForm({initial,categories,onSave}){const [form,setForm]=useState(initial),[error,setError]=useState("");const submit=async e=>{e.preventDefault();try{await onSave(form)}catch(err){setError(err.message)}};return <form className="admin-form" onSubmit={submit}><label>所属分类<select value={form.category_id} onChange={e=>setForm({...form,category_id:e.target.value})} required><option value="">请选择</option>{categories.map(c=><option value={c.id} key={c.id}>{c.label}</option>)}</select></label><label>分组名称<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>排序<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><span/><button className="primary-button">保存分组</button></div></form>}

function CategoryForm({initial,onSave}){const [form,setForm]=useState(initial),[error,setError]=useState("");const submit=async e=>{e.preventDefault();try{await onSave(form)}catch(err){setError(err.message)}};return <form className="admin-form" onSubmit={submit}><div className="form-row"><label>分类名称<input value={form.label} onChange={e=>setForm({...form,label:e.target.value})} required/></label><label>唯一标识<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value.toLowerCase().replace(/\s+/g,"-")})} required/></label></div><label>页面标题<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} required/></label><div className="form-row"><label>排序<input type="number" value={form.sort_order} onChange={e=>setForm({...form,sort_order:e.target.value})}/></label><label className="checkbox-label"><input type="checkbox" checked={Boolean(form.is_visible)} onChange={e=>setForm({...form,is_visible:e.target.checked})}/>在公开站点显示</label></div>{error&&<div className="form-error">{error}</div>}<div className="modal-actions"><span/><button className="primary-button">保存分类</button></div></form>}
